<?php

/**
 * Catálogo de relatórios institucionais da CPED.
 * Sem tabela própria — lê dos models existentes.
 */
return [
    'catalogo' => [
        'resolucoes' => [
            'key' => 'resolucoes',
            'label' => 'Relatório de Resoluções',
            'description' => 'Acompanhe a vigência, os prazos e a situação das resoluções.',
            'api' => '/api/resolucoes',
            'icon' => 'resolucoes',
            'filtros' => ['ano', 'categoria', 'status', 'setor', 'relator'],
            'colunas' => [
                ['key' => 'numero', 'label' => 'Identificador'],
                ['key' => 'resumo', 'label' => 'Resumo'],
                ['key' => 'curso_relacionado', 'label' => 'Curso/Técnico relacionado'],
                ['key' => 'data_inicio_vigencia', 'label' => 'Data de início'],
                ['key' => 'data_fim_vigencia', 'label' => 'Data de vencimento'],
                ['key' => 'status', 'label' => 'Situação da vigência'],
                ['key' => 'categoria', 'label' => 'Categoria'],
                ['key' => 'setor', 'label' => 'Setor'],
                ['key' => 'relator', 'label' => 'Relator'],
            ],
            'preview_keys' => ['numero', 'resumo', 'curso_relacionado', 'data_inicio_vigencia', 'data_fim_vigencia', 'status'],
        ],
        'termos-referencia' => [
            'key' => 'termos-referencia',
            'label' => 'Relatório de Termos de Referência',
            'description' => 'Acompanhe o ciclo de vida, prazos e tramitação dos Termos de Referência.',
            'api' => '/api/termos-referencia',
            'icon' => 'termos-referencia',
            'filtros' => ['eixo', 'status'],
            'colunas' => [
                ['key' => 'nome', 'label' => 'Nome'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'processo_sei', 'label' => 'Processo SEI'],
                ['key' => 'prazo_deadline', 'label' => 'Prazo'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'data_inicio', 'label' => 'Início'],
                ['key' => 'data_fim', 'label' => 'Término'],
                ['key' => 'observacao', 'label' => 'Observação'],
            ],
            'preview_keys' => ['nome', 'eixo', 'processo_sei', 'prazo_deadline', 'status'],
        ],
        'cursos' => [
            'key' => 'cursos',
            'label' => 'Relatório de Cursos',
            'description' => 'Catálogo de cursos importado no portfólio.',
            'api' => '/api/cursos',
            'icon' => 'cursos',
            'filtros' => ['ano', 'unidade', 'eixo', 'status'],
            'colunas' => [
                ['key' => 'titulo', 'label' => 'Título'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'carga_horaria', 'label' => 'CH'],
                ['key' => 'codigo_sig', 'label' => 'Cód. SIG'],
                ['key' => 'processo_sei', 'label' => 'Processo SEI'],
                ['key' => 'tipo', 'label' => 'Tipo'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'ultima_revisao', 'label' => 'Revisão'],
            ],
            'preview_keys' => ['titulo', 'eixo', 'carga_horaria', 'codigo_sig', 'processo_sei', 'tipo', 'status'],
        ],
        'plano-de-metas' => [
            'key' => 'plano-de-metas',
            'label' => 'Relatório de Plano de Metas',
            'description' => 'Metas e entregas do planejamento por segmento e status.',
            'api' => '/api/plano-de-metas',
            'icon' => 'metas',
            'filtros' => ['ano', 'status'],
            'colunas' => [
                ['key' => 'curso', 'label' => 'Curso'],
                ['key' => 'segmento', 'label' => 'Segmento'],
                ['key' => 'tipo', 'label' => 'Tipo'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'status_final', 'label' => 'Status final'],
                ['key' => 'mes_entrega', 'label' => 'Mês'],
                ['key' => 'ano', 'label' => 'Ano'],
                ['key' => 'numero_sei', 'label' => 'SEI'],
            ],
            'preview_keys' => ['curso', 'segmento', 'tipo', 'status', 'ano', 'mes_entrega', 'numero_sei'],
        ],
        'pcas' => [
            'key' => 'pcas',
            'label' => 'Relatório de PCA',
            'description' => 'Cursos previstos no planejamento do período com precificação.',
            'api' => '/api/pcas',
            'icon' => 'pca',
            'filtros' => ['ano', 'unidade', 'eixo', 'status'],
            'colunas' => [
                ['key' => 'titulo', 'label' => 'Título'],
                ['key' => 'semestre', 'label' => 'Semestre'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'carga_horaria', 'label' => 'CH'],
                ['key' => 'valor', 'label' => 'Valor'],
                ['key' => 'numero_sei', 'label' => 'SEI'],
                ['key' => 'ano', 'label' => 'Ano'],
            ],
            'preview_keys' => ['titulo', 'semestre', 'eixo', 'unidade', 'carga_horaria', 'status', 'ano'],
        ],
        'eixos' => [
            'key' => 'eixos',
            'label' => 'Relatório de Eixos',
            'description' => 'Cursos por eixo tecnológico com turmas, alunos e instrutores.',
            'api' => '/api/curso-por-eixos',
            'icon' => 'eixos',
            'filtros' => ['ano', 'unidade', 'eixo', 'status'],
            'colunas' => [
                ['key' => 'curso', 'label' => 'Curso'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'ano', 'label' => 'Ano'],
                ['key' => 'turmas', 'label' => 'Turmas'],
                ['key' => 'alunos', 'label' => 'Alunos'],
                ['key' => 'instrutores', 'label' => 'Instrutores'],
                ['key' => 'status', 'label' => 'Status'],
            ],
            'preview_keys' => ['curso', 'eixo', 'unidade', 'ano', 'turmas', 'alunos', 'status'],
        ],
        'visitas-tecnicas' => [
            'key' => 'visitas-tecnicas',
            'label' => 'Relatório de Visitas Técnicas',
            'description' => 'Solicitações e andamento das visitas técnicas por unidade.',
            'api' => '/api/visitas-tecnicas',
            'icon' => 'visitas',
            'filtros' => ['unidade', 'eixo', 'status'],
            'colunas' => [
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'processo_sei', 'label' => 'SEI'],
                ['key' => 'data_solicitacao', 'label' => 'Solicitação'],
                ['key' => 'prazo_limite', 'label' => 'Prazo'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'responsavel', 'label' => 'Responsável'],
            ],
            'preview_keys' => ['unidade', 'eixo', 'processo_sei', 'responsavel', 'status', 'data_solicitacao'],
        ],
        'horas-pedagogicas' => [
            'key' => 'horas-pedagogicas',
            'label' => 'Relatório de Horas Pedagógicas',
            'description' => 'Controle de horas pedagógicas e processos SEI.',
            'api' => '/api/horas-pedagogicas',
            'icon' => 'horas',
            'filtros' => ['ano', 'eixo', 'status'],
            'colunas' => [
                ['key' => 'pessoa', 'label' => 'Pessoa'],
                ['key' => 'matricula', 'label' => 'Matrícula'],
                ['key' => 'segmento', 'label' => 'Segmento'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'ano', 'label' => 'Ano'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'processo_sei', 'label' => 'SEI'],
                ['key' => 'motivo', 'label' => 'Motivo'],
            ],
            'preview_keys' => ['pessoa', 'matricula', 'eixo', 'ano', 'status', 'processo_sei'],
        ],
        'acoes-extensivas' => [
            'key' => 'acoes-extensivas',
            'label' => 'Relatório de Ações Extensivas',
            'description' => 'Registro e acompanhamento de ações extensivas.',
            'api' => '/api/acoes-extensivas',
            'icon' => 'acoes',
            'filtros' => ['eixo', 'status'],
            'colunas' => [
                ['key' => 'assunto', 'label' => 'Assunto'],
                ['key' => 'tipo', 'label' => 'Tipo'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'status', 'label' => 'Status'],
                ['key' => 'atribuido', 'label' => 'Atribuído'],
                ['key' => 'numero_processo_sei', 'label' => 'SEI'],
                ['key' => 'priorizacao', 'label' => 'Prioridade'],
            ],
            'preview_keys' => ['assunto', 'tipo', 'eixo', 'atribuido', 'status', 'numero_processo_sei'],
        ],
        'eventos' => [
            'key' => 'eventos',
            'label' => 'Relatório de Eventos',
            'description' => 'Eventos realizados por unidade, eixo e período.',
            'api' => '/api/eventos',
            'icon' => 'eventos',
            'filtros' => ['ano', 'unidade', 'eixo', 'status'],
            'colunas' => [
                ['key' => 'nome', 'label' => 'Evento'],
                ['key' => 'ano', 'label' => 'Ano'],
                ['key' => 'data', 'label' => 'Data'],
                ['key' => 'unidade', 'label' => 'Unidade'],
                ['key' => 'eixo', 'label' => 'Eixo'],
                ['key' => 'quantidade_pessoas', 'label' => 'Pessoas'],
                ['key' => 'status', 'label' => 'Status'],
            ],
            'preview_keys' => ['nome', 'data', 'unidade', 'eixo', 'quantidade_pessoas', 'status'],
        ],
    ],
];
